name: Deploy to Preview Channel

on:
  pull_request:
  # Optionally configure to run only for specific files. For example:
  # paths:
  # - "website/**"

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          # registry-url: 'https://npm.pkg.github.com'
          # always-auth: false
          # scope: phaco3d

      - name: Install Dependencies
        run: yarn install
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}

      # - name: Eslint
      #   run: yarn lint

      - name: Build
        run: yarn build
        env:
          CI: false

      - name: Firebase Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          expires: 10d
          projectId: gh-template
          target: template-reactjs-typescript
